// GENERATED by scripts/build-content.mjs — do not edit.
export type Blog = {
  _id: string
  slug: string
  title: string
  summary: string
  publishedAt: string
  readingTime: {
    text: string
    minutes: number
    time: number
    words: number
  }
}

export const allBlogs: Blog[] = [
  {
    "_id": "ce.mdx",
    "slug": "ce",
    "title": "稀奇古怪的中国经济",
    "summary": "这是一篇文章",
    "publishedAt": "2025-12-27T07:36:00",
    "readingTime": {
      "text": "398 min read",
      "minutes": 397.705,
      "time": 23862300,
      "words": 79541
    }
  },
  {
    "_id": "test.mdx",
    "slug": "test",
    "title": "测试",
    "summary": "这是一篇文章",
    "publishedAt": "2025-12-27T07:33:00",
    "readingTime": {
      "text": "1 min read",
      "minutes": 0.02,
      "time": 1200,
      "words": 4
    }
  },
  {
    "_id": "fh.mdx",
    "slug": "fh",
    "title": "战马",
    "summary": "这是一篇文章",
    "publishedAt": "2025-12-27T07:31:00",
    "readingTime": {
      "text": "1 min read",
      "minutes": 0.2,
      "time": 12000,
      "words": 40
    }
  },
  {
    "_id": "analy-react-scripts.mdx",
    "slug": "analy-react-scripts",
    "title": "React脚手架 react-scripts源码分析",
    "summary": "了解react-scripts cli背后的原理，以及自定义自己的webpack打包配置",
    "publishedAt": "2023-12-28",
    "readingTime": {
      "text": "5 min read",
      "minutes": 4.9,
      "time": 294000,
      "words": 980
    }
  },
  {
    "_id": "use-node-reptile.mdx",
    "slug": "use-node-reptile",
    "title": "使用Nodejs多进程分页爬取二次元小姐姐",
    "summary": "通过Nodejs的快捷、简便性，爬取某网站二次元图片下载到本地",
    "publishedAt": "2023-11-23",
    "readingTime": {
      "text": "7 min read",
      "minutes": 6.03,
      "time": 361800,
      "words": 1206
    }
  },
  {
    "_id": "use-nextjs-create-blog.mdx",
    "slug": "use-nextjs-create-blog",
    "title": "使用Nextjs+Tailwind+Contentlayer搭建博客",
    "summary": "🎉 🎉 快速创建个人博客，支持mdx编写、服务端渲染、Github评论、主题切换等功能",
    "publishedAt": "2023-11-15",
    "readingTime": {
      "text": "5 min read",
      "minutes": 4.585,
      "time": 275100,
      "words": 917
    }
  },
  {
    "_id": "decorator.mdx",
    "slug": "decorator",
    "title": "深入理解装饰器",
    "summary": "在编写Nestjs或Angular这类框架的应用时经常会用到装饰器,写篇文章详细讲解一下,弄明白后就可以对Typescript的类反射灵活应用了---写篇文章详细讲解一下,弄明白后就可以对Typescript的类反射灵活应用了",
    "publishedAt": "2023-10-31",
    "readingTime": {
      "text": "27 min read",
      "minutes": 26.88,
      "time": 1612800,
      "words": 5376
    }
  }
]
