// Generates src/content/blog-data.ts from content/*.mdx frontmatter.
//
// Replaces contentlayer (whose CLI is broken on modern Node and whose
// useMDXComponent evals via new Function(), forbidden on Cloudflare Workers).
// MDX bodies are precompiled separately by scripts/compile-mdx.mjs.
import { readFile, writeFile, readdir } from 'node:fs/promises'
import { join, basename } from 'node:path'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const readingTime = require('reading-time')

const root = new URL('../', import.meta.url).pathname
const contentDir = join(root, 'content')

const files = (await readdir(contentDir)).filter((f) => f.endsWith('.mdx'))

function parseFrontmatter(raw) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n/)
  const fields = {}
  if (m) {
    for (const line of m[1].split('\n')) {
      const kv = line.match(/^([a-zA-Z]+):\s*['"]?(.*?)['"]?\s*$/)
      if (kv) fields[kv[1]] = kv[2]
    }
  }
  const body = raw.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, '')
  return { fields, body }
}

const blogs = []
for (const file of files) {
  const slug = basename(file, '.mdx')
  const raw = await readFile(join(contentDir, file), 'utf8')
  const { fields, body } = parseFrontmatter(raw)
  if (!fields.title || !fields.publishedAt || !fields.summary) {
    throw new Error(`${file}: missing required frontmatter (title/publishedAt/summary)`)
  }
  const rt = readingTime(body)
  blogs.push({
    _id: file,
    slug,
    title: fields.title,
    summary: fields.summary,
    publishedAt: fields.publishedAt,
    readingTime: {
      text: rt.text,
      minutes: rt.minutes,
      time: rt.time,
      words: rt.words,
    },
  })
}

// Newest first, matching the homepage/feed sort order.
blogs.sort((a, b) => (new Date(a.publishedAt) > new Date(b.publishedAt) ? -1 : 1))

const out = `// GENERATED by scripts/build-content.mjs — do not edit.
export type Blog = {
  _id: string
  slug: string
  title: string
  summary: string
  publishedAt: string
  readingTime: {
    text: string
    minutes: number
    time: number
    words: number
  }
}

export const allBlogs: Blog[] = ${JSON.stringify(blogs, null, 2)}
`

await writeFile(join(root, 'src', 'content', 'blog-data.ts'), out)
console.log(`wrote src/content/blog-data.ts with ${blogs.length} posts`)
